import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Scheduling app",
  description: "Generated by create next app",
};

const PageLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="flex flex-col border-border-orange">
      {children}
    </div>)
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageLayout>
          {children}
        </PageLayout>
      </body>
    </html>
  );
}

